In [3]:
import snowflake.connector
# Gets the version
import  pandas as pd
import numpy as np
from tqdm import tqdm


In [4]:
import requests
r = requests.get('http://ocsp.digicert.com/')
r.text

'<html>\n<body>\n\tCRL Repository\n</body>\n</html>\n'

In [5]:
ACCOUNT =  "po91914.east-us-2.azure"
USER =  "_sdatabricks_service"
PASSWORD = "DBDcpSCab@2018!2"

sfDatabase="DATAWAREHOUSE_DB",
sfSchema="SYSTEM_OPTIMIZATION",
sfWarehouse="DATABRICKS_WH"

In [6]:
ctx = snowflake.connector.connect(
    user=USER,
    password=PASSWORD,
    account=ACCOUNT,
    insecure_mode=True
    )
ctx.cursor().execute('USE warehouse DATABRICKS_WH')
ctx.cursor().execute('USE DATAWAREHOUSE_DB.SYSTEM_OPTIMIZATION')


cur = ctx.cursor()
ROW = []
try:
    cur.execute('SELECT * FROM "DATAWAREHOUSE_DB"."SYSTEM_OPTIMIZATION"."V_METER_COEFFICIENTS"')
    coeff = pd.DataFrame.from_records(iter(cur), columns=[x[0] for x in cur.description])
    
    cur.execute('SELECT * FROM "DATAWAREHOUSE_DB"."SYSTEM_OPTIMIZATION"."V_BOOSTER_COEFFICIENTS"')
    reference_booster = pd.DataFrame.from_records(iter(cur), columns=[x[0] for x in cur.description])
    
    cur.execute('SELECT * FROM "DATAWAREHOUSE_DB"."SYSTEM_OPTIMIZATION"."V_PLANT_COEFFICIENTS"')
    reference_plant = pd.DataFrame.from_records(iter(cur), columns=[x[0] for x in cur.description])
    
    cur.execute('SELECT * FROM "DATAWAREHOUSE_DB"."SYSTEM_OPTIMIZATION"."V_PRICING_COEFFICIENTS"')
    reference_price = pd.DataFrame.from_records(iter(cur), columns=[x[0] for x in cur.description])
    
    cur.execute('SELECT * FROM "DATAWAREHOUSE_DB"."SYSTEM_OPTIMIZATION"."V_STATIC_REFERENCE_DATA"')
    reference_static = pd.DataFrame.from_records(iter(cur), columns=[x[0] for x in cur.description])
    
    cur.execute('SELECT * FROM "DATAWAREHOUSE_DB"."SYSTEM_OPTIMIZATION"."V_ROUTING"')
    reference_routing = pd.DataFrame.from_records(iter(cur), columns=[x[0] for x in cur.description])
    
    cur.execute('SELECT * FROM "DATAWAREHOUSE_DB"."SYSTEM_OPTIMIZATION"."V_OPEX"')
    reference_opex = pd.DataFrame.from_records(iter(cur), columns=[x[0] for x in cur.description])
        
finally:
    cur.close()
reference_plant[reference_plant.PLANT == 'Pegasus']

DATE    PLANT           C2_PCT_RECOVERY           C3_PCT_RECOVERY  \
81    8/1/2018  Pegasus  0.7094300840000000000000  0.9730551910000000000000   
180   9/1/2018  Pegasus  0.7094300840000000000000  0.9730551910000000000000   
279  10/1/2018  Pegasus  0.7094300840000000000000  0.9730551910000000000000   
378  11/1/2018  Pegasus  0.7094300840000000000000  0.9730551910000000000000   
477  12/1/2018  Pegasus  0.7094300840000000000000  0.9730551910000000000000   
576   1/1/2019  Pegasus  0.7094300840000000000000  0.9730551910000000000000   

             IC4_PCT_RECOVERY          NC4_PCT_RECOVERY  \
81   1.0000000000000000000000  1.0000000000000000000000   
180  1.0000000000000000000000  1.0000000000000000000000   
279  1.0000000000000000000000  1.0000000000000000000000   
378  1.0000000000000000000000  1.0000000000000000000000   
477  1.0000000000000000000000  1.0000000000000000000000   
576  1.0000000000000000000000  1.0000000000000000000000   

              C5_PCT_RECOVERY           C6_PCT_RECOVERY HE_PCT_RECOVERY  \
81   1.0000000000000000000000  1.0000000000000000000000           0E-22   
180  1.0000000000000000000000  1.0000000000000000000000           0E-22   
279  1.0000000000000000000000  1.0000000000000000000000           0E-22   
378  1.0000000000000000000000  1.0000000000000000000000           0E-22   
477  1.0000000000000000000000  1.0000000000000000000000           0E-22   
576  1.0000000000000000000000  1.0000000000000000000000           0E-22   

      CONDENSATE_PCT_RECOVERY        ...          \
81   0.0800000000000000000000        ...           
180  0.0800000000000000000000        ...           
279  0.0800000000000000000000        ...           
378  0.0800000000000000000000        ...           
477  0.0800000000000000000000        ...           
576  0.0800000000000000000000        ...           

                              DCP_NGL_MARKET1_C2  \
81   Monthly Avg Mont Belvieu C2 (Purity) nonTET   
180  Monthly Avg Mont Belvieu C2 (Purity) nonTET   
279  Monthly Avg Mont Belvieu C2 (Purity) nonTET   
378  Monthly Avg Mont Belvieu C2 (Purity) nonTET   
477  Monthly Avg Mont Belvieu C2 (Purity) nonTET   
576  Monthly Avg Mont Belvieu C2 (Purity) nonTET   

                     DCP_NGL_MARKET1_C3                  DCP_NGL_MARKET1_IC4  \
81   Monthly Avg Mont Belvieu C3 nonTET  Monthly Avg Mont BelvieuI C4 nonTET   
180  Monthly Avg Mont Belvieu C3 nonTET  Monthly Avg Mont BelvieuI C4 nonTET   
279  Monthly Avg Mont Belvieu C3 nonTET  Monthly Avg Mont BelvieuI C4 nonTET   
378  Monthly Avg Mont Belvieu C3 nonTET  Monthly Avg Mont BelvieuI C4 nonTET   
477  Monthly Avg Mont Belvieu C3 nonTET  Monthly Avg Mont BelvieuI C4 nonTET   
576  Monthly Avg Mont Belvieu C3 nonTET  Monthly Avg Mont BelvieuI C4 nonTET   

                     DCP_NGL_MARKET1_NC4 DCP_NGL_MARKET1_C5  \
81   Monthly Avg Mont Belvieu NC4 nonTET  MoMBNTETC5+NonTET   
180  Monthly Avg Mont Belvieu NC4 nonTET  MoMBNTETC5+NonTET   
279  Monthly Avg Mont Belvieu NC4 nonTET  MoMBNTETC5+NonTET   
378  Monthly Avg Mont Belvieu NC4 nonTET  MoMBNTETC5+NonTET   
477  Monthly Avg Mont Belvieu NC4 nonTET  MoMBNTETC5+NonTET   
576  Monthly Avg Mont Belvieu NC4 nonTET  MoMBNTETC5+NonTET   

    DCP_NGL_MARKET2_C2 DCP_NGL_MARKET2_C3 DCP_NGL_MARKET2_IC4  \
81                None               None                None   
180               None               None                None   
279               None               None                None   
378               None               None                None   
477               None               None                None   
576               None               None                None   

    DCP_NGL_MARKET2_NC4 DCP_NGL_MARKET2_C5  
81                 None               None  
180                None               None  
279                None               None  
378                None               None  
477                None               None  
576                None               None  

[6 rows x 4

In [7]:
coeff = coeff[~coeff.ROUTE_NUMBER.isnull()]

In [8]:
coeff = coeff.reset_index(drop = True)
len(coeff['TIPS_METER'])

253920

In [9]:
coeff = coeff.replace(np.nan, 0)
reference_plant = reference_plant.replace(np.nan, 0)
reference_price = reference_price.replace(np.nan, 0)
reference_booster = reference_booster.replace(np.nan, 0)
reference_opex = reference_opex.replace(np.nan, 0)
reference_static = reference_static.replace(np.nan, 0)

coeff['DATE'] = pd.to_datetime(coeff['DATE'])
reference_price['DATE'] = pd.to_datetime(reference_price['DATE'])
reference_plant['DATE'] = pd.to_datetime(reference_plant['DATE'])
reference_booster['DATE'] = pd.to_datetime(reference_booster['DATE'])
reference_routing['DATE'] = pd.to_datetime(reference_routing['DATE'])
reference_opex['DATE'] = pd.to_datetime(reference_opex['DATE'])


In [10]:
rec_dcp_dict = {}
rec_prod_dict={}

In [11]:
TIPs_Meter = '701632-0000'
#'13135198'#'6375711'#'13135172'#'75118'
date1 = '2019-01-01 00:00:00'
#date2 = '2019-01-01 00:00:00'
print()
Coeff = coeff[coeff['DATE'] == date1].reset_index(drop = True)
Price = reference_price[reference_price['DATE'] == date1].reset_index(drop = True)
Plant = reference_plant[reference_plant['DATE'] == date1].reset_index(drop = True)
Booster = reference_booster[reference_booster['DATE'] == date1].reset_index(drop = True)
Route = reference_routing[reference_routing['DATE'] == date1].reset_index(drop = True)
Opex = reference_opex[reference_opex['DATE'] == date1].reset_index(drop = True)
Static = reference_static

In [12]:
print (len(pd.unique(Coeff['ROUTE_NUMBER'])))
print (len(Coeff))
Coeff.ROUTE_NUMBER.values

319
42320


array([50561, 30021, 30021, ..., 40181, 41311, 40721], dtype=int64)

In [13]:
def Converting_to_float(df):
    for column in df.columns:
        try:
            df[column] = pd.to_numeric(df[column],  errors='ignore')
 
        except:
            pass
      
    return df

In [14]:
Converting_to_float(Coeff)
Converting_to_float(Booster)
Converting_to_float(Price)
Converting_to_float(Route)
Converting_to_float(Opex)
Converting_to_float(Static)
Converting_to_float(Plant)

DATE               PLANT  C2_PCT_RECOVERY  C3_PCT_RECOVERY  \
0   1546300800000000000      Anderson Gulch         0.500000         0.800000   
1   1546300800000000000              Antrim         0.500000         0.800000   
2   1546300800000000000             Artesia         0.801860         0.990131   
3   1546300800000000000            Beaumont         0.917712         0.949727   
4   1546300800000000000       Black Diamond         0.891100         0.994000   
5   1546300800000000000            Chitwood         0.711231         0.964333   
6   1546300800000000000            Cimarron         0.792393         0.997550   
7   1546300800000000000          Crossroads         0.000000         0.000000   
8   1546300800000000000  DTS Anderson Gulch         0.000000         0.000000   
9   1546300800000000000          DTS Antrim         0.000000         0.000000   
10  1546300800000000000         DTS Artesia         0.000000         0.000000   
11  1546300800000000000        DTS Beaumont         0.000000         0.000000   
12  1546300800000000000   DTS Black Diamond         0.000000         0.000000   
13  1546300800000000000        DTS Chitwood         0.000000         0.000000   
14  1546300800000000000        DTS Cimarron         0.000000         0.000000   
15  1546300800000000000      DTS Crossroads         0.000000         0.000000   
16  1546300800000000000           DTS Eagle         0.000000         0.000000   
17  1546300800000000000      DTS East Texas         0.000000         0.000000   
18  1546300800000000000          DTS Eunice         0.000000         0.000000   
19  1546300800000000000             DTS Fox         0.000000         0.000000   
20  1546300800000000000       DTS Fullerton         0.000000         0.000000   
21  1546300800000000000        DTS Giddings         0.000000         0.000000   
22  1546300800000000000       DTS Goldsmith         0.000000         0.000000   
23  1546300800000000000          DTS Goliad         0.000000         0.000000   
24  1546300800000000000         DTS Greeley         0.000000         0.000000   
25  1546300800000000000     DTS Gulf Plains         0.000000         0.000000   
26  1546300800000000000      DTS Kingfisher         0.000000         0.000000   
27  1546300800000000000       DTS La Gloria         0.000000         0.000000   
28  1546300800000000000    DTS Ladder Creek         0.000000         0.000000   
29  1546300800000000000     DTS Linam Ranch         0.000000         0.000000   
..                  ...                 ...              ...              ...   
69  1546300800000000000        Ladder Creek         0.288457         0.461487   
70  1546300800000000000         Linam Ranch         0.725410         0.985782   
71  1546300800000000000             Lucerne         0.500000         0.800000   
72  1546300800000000000           Lucerne 2         0.500000         0.800000   
73  1546300800000000000            Mewbourn         0.500000         0.800000   
74  1546300800000000000          Mewbourn 3         0.500000         0.800000   
75  1546300800000000000          Mobile Bay         0.066118         0.980149   
76  1546300800000000000             Mustang         0.674322         0.971216   
77  1546300800000000000     National Helium         0.754108         0.828951   
78  1546300800000000000             Oconnor         0.890240         0.986910   
79  1546300800000000000                OGPP         0.840000         0.970000   
80  1546300800000000000             Okarche         0.792393         0.997550   
81  1546300800000000000             Pegasus         0.709430         0.973055   
82  1546300800000000000         Platteville         0.500000         0.800000   
83  1546300800000000000         Port Arthur         0.550000         0.980000   
84  1546300800000000000             Rawhide         0.784617         0.991614   
85  1546300800000000000       Roberts Ranch         0.799829         0.967063   
86  1546300800000000000          Rock Creek       

In [15]:
def Asset_from_Routing(meter):
    route = int(Coeff.loc[meter]['ROUTE_NUMBER'])
   
    b1 = Route[Route['ROUTE_NUMBER'] == route]['BOOSTER_NAME'].values[0]
    b2 = Route[Route['ROUTE_NUMBER'] == route]['SECONDARY_BOOSTER'].values[0]
    b3 = Route[Route['ROUTE_NUMBER'] == route]['TERTIARY_BOOSTER'].values[0]
    p = Route[Route['ROUTE_NUMBER'] == route]['PLANT_NAME'].values[0]
    gs = Route[Route['ROUTE_NUMBER'] == route]['GATHERING_SYSTEM'].values[0]
    a = Route[Route['ROUTE_NUMBER'] == route]['AREA'].values[0]
    return [route,b1,b2,b3,p,gs,a]
    

## Choosing meter only for one AREA

In [16]:
len(Coeff[Coeff.AREA == 'SENM'])
area = pd.unique(Coeff.AREA)
n=0
for a in area:
    print(a,len(Coeff[Coeff.AREA == a]) )
    n = n+len(Coeff[Coeff.AREA == a])
print (n)

SENM 3760
DJ Basin 6306
Goldsmith_Fullerton 4814
Liberal 6042
Ozona 2121
Arklatex 517
Panhandle 5176
Southern Oklahoma 2987
Michigan 1086
Triad 1387
SCTX 2062
Barnett Shale 81
Gulf Coast 168
Central Oklahoma 5813
42320


In [17]:
Coeff = Coeff[Coeff.AREA == 'SENM'].reset_index(drop = True)
print (len(Coeff))


3760


## DCP side

In [18]:
def LU(meter):
    route,b1,b2,b3,p,gs,a = Asset_from_Routing(meter)
    
    if (b1!=0) and (b1 in Booster['BOOSTER'].values):
        return Booster[Booster['BOOSTER']==b1]['ACTUAL_LU_TO_BOOSTER_PCT'].values[0]
    else:
        return 0.0

def Fuel(meter):
    route,b1,b2,b3,p,gs,a = Asset_from_Routing(meter)
    if (b1!=0) and (b1 in Booster['BOOSTER'].values):
        return Booster[Booster['BOOSTER']== b1]['ACTUAL_FUEL_TO_BOOSTER_PCT'].values[0]
    else: 
        return 0.0

def total_MCF(meter):
    return Coeff.loc[meter]['MCF']

def total_MMBTU(meter):
    #return coeff.loc[meter]['MCF']*coeff.loc[meter]['BTU']
    return Coeff.loc[meter]['MMBTU']

In [19]:
# print (Asset_from_Routing(2)[1])
# Fuel(2)
# Booster[Booster.BOOSTER == 'Bell Lake Bstr']
Fuel(3)
LU(3)


0.09

In [20]:
def Net_delivered_mcf(meter):
    LU_mcf = total_MCF(meter)*LU(meter)
    Fuel_mcf = total_MCF(meter)*Fuel(meter)
    Net_deliv_mcf = total_MCF(meter)-LU_mcf-Fuel_mcf
    return (Net_deliv_mcf)
  
def Net_delivered_mmbtu(meter):
    LU_mmbtu = total_MMBTU(meter)*LU(meter)
    Fuel_mmbtu = total_MMBTU(meter)*Fuel(meter)
    Net_deliv_mmbtu = total_MMBTU(meter)- LU_mmbtu-Fuel_mmbtu
    return (Net_deliv_mmbtu)

In [21]:
Net_delivered_mcf(82)

541.12

In [22]:
def Recovery_DCP(meter,frac):
    #route,b1,b2,b3,p,gs,a = Asset_from_Routing(meter)
    if frac in rec_dcp_dict:
        recovery = rec_dcp_dict[frac][0]
        theoreticalG = rec_dcp_dict[frac][1]
        recoveredG = rec_dcp_dict[frac][2]
        shrink = rec_dcp_dict[frac][3]
        
        #print("     Recovery_DCP done (from dict)")    
        return recovery,theoreticalG, recoveredG, shrink
        
    else:
        p = Asset_from_Routing(meter)[4]
        recovery = Plant[Plant['PLANT']==p][frac+'_PCT_RECOVERY'].values
        rec_dcp_dict[frac] = [recovery]

        if frac == 'HE':
            theoreticalG = Net_delivered_mcf(meter)*Coeff.loc[meter][frac+'_MOL_PCT']/100.0#Fraction(meter,'He')[0]#*1000
            recoveredG = theoreticalG*recovery
            shrink = 0.0
        else:
            theoreticalG = Net_delivered_mcf(meter)*Coeff.loc[meter][str(frac)+'_GPM'] 
            recoveredG = theoreticalG*recovery
            shrink = recoveredG*Static[Static['PRODUCT'] == frac]['SHRINK_FACTOR'].values
        rec_dcp_dict[frac].append(theoreticalG)
        rec_dcp_dict[frac].append(recoveredG)
        rec_dcp_dict[frac].append(shrink)
        #print("     Recovery_DCP done")    
        return recovery,theoreticalG, recoveredG, shrink
        
        
    return recovery,theoreticalG, recoveredG, shrink
    
def DCP_Recovery_Total(meter):
    fractions = ['C2', 'C3', 'IC4', 'NC4', 'C5', 'C6']

    net_theoreticalG =[]
    net_recoveredG = []
    net_shrink =[]
   
    for frac in fractions:
        recovery,theoreticalG, recoveredG, shrink = Recovery_DCP(meter, frac)
   
        net_theoreticalG.append(theoreticalG)
        net_recoveredG.append(recoveredG)
        net_shrink.append(shrink)
    
        #print (frac, 'recovery %', recovery*100, '  Theoretical G', theoreticalG, '   Recovered G', recoveredG)
    total_net_theoretical_G = sum(net_theoreticalG)
    total_net_recovered_G= sum(net_recoveredG)
    total_shrink = sum(net_shrink)
    
  
    return total_net_theoretical_G, total_net_recovered_G, total_shrink

In [23]:
print (Asset_from_Routing(175))
print (Coeff.TIPS_METER[175])
print (DCP_Recovery_Total(1))

[51291, 'Dobbs_Lovington', nan, nan, 'Linam Ranch', 'Linam Ranch Gathering', 'SENM']
014288ST
(5576.756909999999, array([4699.33254276]), array([392.85949049]))


In [24]:
def DCP_NGL_market(meter,market):
    #route,b1,b2,b3,plant,gs,a = Asset_from_Routing(meter)
    plant = Asset_from_Routing(meter)[4]
    fractions_NGL = ['C2', 'C3', 'IC4','NC4', 'C5']
    DCP_market_index = []
    price = []
    if plant in Plant['PLANT'].values and plant != 0:
        for frac in fractions_NGL:
            index = Plant[Plant['PLANT']==plant]['DCP_NGL_MARKET'+str(market)+'_'+str(frac)].values[0]
            DCP_market_index.append(index)
            if index!= 0.0:
#             print(index)
                p = Price[Price['INDEX'] == index]['PRICE'].values
                price.append(p)
            else:
                price.append(0.0)
        pct = Plant[Plant['PLANT']==plant]['DCP_NGL_MARKET_'+str(market)+'_PCT'].values
        tf = Plant[reference_plant['PLANT']==plant]['DCP_TF_ON_NGL_MARKET_'+str(market)].values[0]
        return (DCP_market_index,price, pct, tf)
#     else:
#         return 0.0,0.0,0.0,0.0

def DCP_NTP(meter):
    
    fractions_NGL = ['C2', 'C3', 'IC4','NC4', 'C5']
    Market1 = DCP_NGL_market(meter,1)
    Market2 = DCP_NGL_market(meter,2)
    dcp_ntp = []
    dcp_tf = []
    for i in range(len(fractions_NGL)):
        
        m1 = (Market1[1][i]+Market1[3])*Market1[2]
        m2 = (Market2[1][i]+Market2[3])*Market2[2]
        m = m1+m2
       
        dcp_ntp.append(m)
        dcp_tf.append(Market1[3])
    return dcp_ntp, dcp_tf



def DCP_res_index(meter):
    
    DCP_RES_index = []
    for ind in range(5):
        DCP_RES_index.append(Plant[Plant['PLANT']==Coeff.loc[meter]['PLANT_NAME']]['DCP_RES_INDEX_'+str(ind+1)].values)
    DCP_RES_deduct = []
    for ind in range(5):
        DCP_RES_deduct.append(Plant[Plant['PLANT']==Coeff.loc[meter]['PLANT_NAME']]['DCP_RES_DEDUCT_INDEX_'+str(ind+1)].values)
    DCP_RES_pct = []
    for ind in range(5):
        DCP_RES_pct.append(Plant[Plant['PLANT']==Coeff.loc[meter]['PLANT_NAME']]['DCP_RES_INDEX_'+str(ind+1)+'_PCT'].values)
        
    return (DCP_RES_index, DCP_RES_deduct, DCP_RES_pct)


In [25]:
DCP_NGL_market(3,1) ### meter Plant_Name is not in PLANT table
DCP_res_index(3)
DCP_NTP(3)### meter Plant_Name is not in PLANT table

C:\Users\ODmitriyeva\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.


([array([0.168244]),
  array([0.519286]),
  array([0.675744]),
  array([0.666458]),
  array([0.8975])],
 [-0.14, -0.14, -0.14, -0.14, -0.14])

In [26]:
def Uplift_DCP(meter):
    #route,b1,b2,b3,plant,gs,a = Asset_from_Routing(meter)
    plant = Asset_from_Routing(meter)[4]
    if plant in Plant['PLANT'].values and plant != 0:
        index = Plant[Plant['PLANT']== plant]['UPLIFT_PIPELINE'].values[0]
        
        #print (index)
        if index!= 0.0:
            price = Price[Price['INDEX'] == index]['PRICE'].values[0]
        else:
            price = 0.0
        uplift = DCP_Recovery_Total(meter)[1]*price
        return uplift
    else:
        return []

In [27]:
Uplift_DCP(4)


array([0.])

In [28]:
def DCP_NGL_Revenue(meter):
    
    fractions = ['C2', 'C3', 'IC4', 'NC4', 'C5', 'C6']

    recoveries = []
    net_recovered_theoreticalG =[]
    net_recoveredG = []
    net_shrink =[]
   
    for frac in fractions:
        recovery,theoreticalG, recoveredG, shrink = Recovery_DCP(meter, frac)
        
        recoveries.append(recovery)
        net_recovered_theoreticalG.append(theoreticalG)
        net_recoveredG.append(recoveredG)
        net_shrink.append(shrink)
    
    
   
    total_net_recovered_theoretical_G, total_net_recovered_G, total_shrink = DCP_Recovery_Total(meter)

  
    fractions_NGL = ['C2', 'C3', 'IC4', 'NC4', 'C56']
    NGL_net_recoveredG = list(net_recoveredG)
    C56 = NGL_net_recoveredG[4]+NGL_net_recoveredG[5]
    NGL_net_recoveredG[4] = C56


    MARKETS = [1,2]
    DCP_NGL_revenue_Market = []
    price_Market = []
    for market in MARKETS:
        NGL_INDEX, PRICE, pct, tf = DCP_NGL_market(meter,market)
        price_Market.append(PRICE)
       
     
    
        #if len([PRICE])>1:
        for i in range(len(fractions_NGL)):
    ####### Do for each fraction recoveredG 
            
            NGL_fraction_revenue = (PRICE[i]+tf)*pct*NGL_net_recoveredG[i]
            
            DCP_NGL_revenue_Market.append(NGL_fraction_revenue[0])
            #print(fractions_NGL[i],'Price: ',PRICE[i], "     tf: ", tf, ' NGL revenue', NGL_fraction_revenue[0])
    Revenue_DCP_NGL = sum(DCP_NGL_revenue_Market)
#     print()
#     print ('total DCP_NGL_revenue ', Revenue_DCP_NGL)
#     print('*************************************')

    
    return Revenue_DCP_NGL, recoveries, net_recovered_theoreticalG,sum(net_recovered_theoreticalG), net_recoveredG, sum(net_recoveredG)

In [29]:
DCP_NGL_Revenue(3)

C:\Users\ODmitriyeva\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.


(1961.749233969518,
 [array([0.72541035]),
  array([0.98578218]),
  array([1.]),
  array([1.]),
  array([1.]),
  array([1.])],
 [3133.6277,
  1193.054345,
  240.96171500000003,
  432.530655,
  301.85863,
  274.72386500000005],
 5576.756909999999,
 [array([2273.16596349]),
  array([1176.09171427]),
  array([240.961715]),
  array([432.530655]),
  array([301.85863]),
  array([274.723865])],
 array([4699.33254276]))

In [30]:
def DCP_Condensate_Revenue(meter):
    #route,b1,b2,b3,plant,gs,a = Asset_from_Routing(meter)
    plant = Asset_from_Routing(meter)[4]
    fractions_Condensate = ['C5', 'C6']
    condensate_recovered_theoretical_G = 0
    condensate_recovered_G = 0

    for frac in fractions_Condensate:
        recovery,theoreticalG, recoveredG, shrink = Recovery_DCP(meter, frac)
        condensate_recovered_theoretical_G += theoreticalG
        condensate_recovered_G += recoveredG
    if len(Plant[Plant['PLANT']== plant]['CONDENSATE_PCT_RECOVERY'].values) >0:
    
    #print ('Recovered C5 + C6 gallons',condensate_recovered_G)
        condensate_recovery = Plant[Plant['PLANT']==plant]['CONDENSATE_PCT_RECOVERY'].values[0]
    #print ('Condensate Recovery %',condensate_recovery)
        DCP_condensate_G = condensate_recovered_G*condensate_recovery  
        DCP_condensate_barrels = DCP_condensate_G/42.
        price = Price[Price['INDEX'] == 'NYMEX - Crude']['PRICE'].values[0]
        diff = Plant[Plant['PLANT']==Coeff.loc[meter]['PLANT_NAME']]['DCP_CONDENSATE_DIFF'].values[0]
   
        Revenue_DCP_Condensate = (price+diff)*DCP_condensate_barrels#[0]
    #print ('DCP Condensate Revenue', Revenue_DCP_Condensate)
        return Revenue_DCP_Condensate, DCP_condensate_barrels[0], price+diff
    else:
        return 0.0 ## or empty array

In [31]:
DCP_Condensate_Revenue(1)

(array([38.65848347]), 1.0982523714285717, 35.2)

In [32]:
def DCP_RES_Revenue(meter):
    
    #route,b1,b2,b3,plant,gs,a = Asset_from_Routing(meter)
    plant = Asset_from_Routing(meter)[4]
    Plant_fuel_DCP_mmbtu = Net_delivered_mmbtu(meter)*Plant[Plant['PLANT']==plant]['PLANT_FUEL_PCT_MMBTU'].values
    total_shrink = DCP_Recovery_Total(meter)[2]

    RES_AFS = Net_delivered_mmbtu(meter)-total_shrink-Plant_fuel_DCP_mmbtu

    INDEX,DEDUCT,PCT = DCP_res_index(meter)
  
    Revenue_DCP_RES = 0.0
    for i in range(5):
        if INDEX[i] != 0:
        
            price = Price[Price['INDEX'] == INDEX[i][0]]['PRICE'].values[0]
            
            for_each_index = (price+DEDUCT[i][0])*PCT[i][0]*RES_AFS[0]
            Revenue_DCP_RES += for_each_index

#     print ('RES - REVENUE_DCP ', Revenue_DCP_RES)

#     print ('***************************************')
#     print ()
    return Revenue_DCP_RES,total_shrink[0], Plant[Plant['PLANT']==plant]['PLANT_FUEL_PCT_MMBTU'].values[0], RES_AFS[0]

In [33]:
DCP_RES_Revenue(67)

(-793.5761707921001, 392.8594904911387, 0.05, -392.8594904911387)

In [34]:
def DCP_RES_Price(meter):
    
    INDEX,DEDUCT,PCT = DCP_res_index(meter)
    price_res = 0.0
    for i in range(5):
        if INDEX[i] != 0:
        
            price = (Price[Price['INDEX'] == INDEX[i][0]]['PRICE'].values[0]+DEDUCT[i][0])*PCT[i][0]
            price_res += price
    return price_res

In [35]:
DCP_RES_Price(3)
#Coeff.loc[1]['TIPS_METER']

2.065

In [36]:
DCP_RES_Revenue(3)
# INDEX = ['NNG Demarc - IFGMR']

# Price[Price['INDEX'] == INDEX[0]]['PRICE'].values[0]

(-811.2548478642013, 392.8594904911387, 0.045, -392.8594904911387)

In [37]:
def DCP_He_Revenue(meter):
    #route,b1,b2,b3,plant,gs,a = Asset_from_Routing(meter)
    
    plant = Asset_from_Routing(meter)[4]
    He_recovery = Recovery_DCP(meter,'HE')[0]
    DCP_He_produced = Recovery_DCP(meter,'HE')[2]
    index = Plant[Plant['PLANT']==plant]['HE_INDEX'].values[0]
    price = Price[Price['INDEX']==index]['PRICE'].values

   #print ('He price', price)
    Revenue_DCP_He = DCP_He_produced*price
    #print ('DCP He Revenue ',Revenue_DCP_He)
    return Revenue_DCP_He[0],DCP_He_produced,price

In [38]:
DCP_He_Revenue(1)



(0.0, array([0.]), array([119.]))

In [39]:
def DCP_Fees(meter):
    return Coeff.loc[meter]['FEES']

In [40]:
def DCP_Revenue(meter): # +DCP_He_Revenue(meter)[0] +Uplift_DCP(meter)
    dcp_revenue = DCP_NGL_Revenue(meter)[0]+DCP_RES_Revenue(meter)[0] + DCP_He_Revenue(meter)[0] +Uplift_DCP(meter)+ DCP_Condensate_Revenue(meter)[0] + DCP_Fees(meter)
    return dcp_revenue

In [41]:
print (DCP_Revenue(82))#,DCP_NGL_Revenue(2)[0], DCP_RES_Revenue(2)[0], DCP_Condensate_Revenue(2)[0], Uplift_DCP(2),  DCP_Fees(2))

C:\Users\ODmitriyeva\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.


[3073.11433476]


## Producer

In [42]:
def LU_producer(meter):
    if Coeff.loc[meter]['LU'] == 'ACTUAL':
        return LU(meter)
    
    else:
        LU_coefficient = Coeff.loc[meter]['PRODUCER_LU_PCT']
        return LU_coefficient

def Fuel_producer(meter):
    if Coeff.loc[meter]['FIELD_FUEL'] == 'ACTUAL':
       
        return Fuel(meter)
    else: 
        Fuel_coefficient = Coeff.loc[meter]['PRODUCER_FIELD_FUEL_PCT']
        return Fuel_coefficient
    
def Producer_Net_delivered_mcf(meter):
    LU_mcf = total_MCF(meter)*LU_producer(meter)
    Fuel_mcf = total_MCF(meter)*Fuel_producer(meter)
    Net_deliv_mcf = total_MCF(meter)-LU_mcf-Fuel_mcf
    return (Net_deliv_mcf)
  
def Producer_Net_delivered_mmbtu(meter):
    LU_mmbtu = total_MMBTU(meter)*LU_producer(meter)
    Fuel_mmbtu = total_MMBTU(meter)*Fuel_producer(meter)
    Net_deliv_mmbtu = total_MMBTU(meter)- LU_mmbtu-Fuel_mmbtu
    return (Net_deliv_mmbtu)

 
 
 

In [43]:
print (Fuel_producer(66))
Producer_Net_delivered_mcf(66)
# total_MCF(6736)
# Coeff.loc[6736]['FIELD_FUEL']
# Coeff.loc[6736]['PRODUCER_FIELD_FUEL_PCT']


0.07


0.0

In [44]:
   
    
def Recovery_Producer(meter, name):
    if name == 'HE':   
        if name in rec_prod_dict:
            recovery = rec_prod_dict[name][0]
            theoreticalG = rec_prod_dict[name][1]
            recoveredG = rec_prod_dict[name][2]
            shrink = rec_prod_dict[name][3]
            #print("     Recovery_Producer done {from dict}")             
            return recovery, theoreticalG, recoveredG, shrink
        else:
            recovery = Coeff.loc[meter]['PRODUCER_HE_PCT_RECOVERY']
            theoreticalG = Producer_Net_delivered_mcf(meter)*Coeff.loc[meter]['HE_MOL_PCT']/100.0
            recoveredG = theoreticalG*recovery
            shrink = 0  
            rec_prod_dict[name] = [recovery]
            rec_prod_dict[name].append(theoreticalG)
            rec_prod_dict[name].append(recoveredG)
            rec_prod_dict[name].append(shrink)
            #print("     Recovery_Producer done")             
            return recovery, theoreticalG, recoveredG, shrink
                          
    elif Coeff.loc[meter]['RECOVERIES'] == 'ACTUAL':
        #print("     Recovery_Producer done")
        return Recovery_DCP(meter,name)
    else:
        if name in rec_prod_dict:
            recovery = rec_prod_dict[name][0]
            theoreticalG = rec_prod_dict[name][1]
            recoveredG = rec_prod_dict[name][2]
            shrink = rec_prod_dict[name][3]
           # print("     Recovery_Producer done (from dict)")             
            return recovery, theoreticalG, recoveredG, shrink
        else:
            recovery = Coeff.loc[meter]['PRODUCER_'+name+'_PCT_RECOVERY']
            theoreticalG = Coeff.loc[meter][str(name)+'_GPM']*Producer_Net_delivered_mcf(meter)
            recoveredG = theoreticalG*recovery
            shrink = recoveredG*Static[Static['PRODUCT'] == name]['SHRINK_FACTOR'].values
            rec_prod_dict[name] = [recovery]
            rec_prod_dict[name].append(theoreticalG)
            rec_prod_dict[name].append(recoveredG)
            rec_prod_dict[name].append(shrink)
            #print("     Recovery_Producer done")
            return recovery, theoreticalG, recoveredG, shrink   
    
def Producer_Recovery_Total(meter):
    fractions = ['C2', 'C3', 'IC4', 'NC4', 'C5', 'C6']

    Producer_recovered_theoreticalG =[]
    Producer_recoveredG = []
    Producer_shrink =[]
    
   
    for frac in fractions:
        recovery,theoreticalG, recoveredG, shrink = Recovery_Producer(meter, frac)
        
        
        Producer_recovered_theoreticalG.append(theoreticalG)
        Producer_recoveredG.append(recoveredG)
        Producer_shrink.append(shrink)
    
        #print (frac, 'recovery %', recovery*100, '  Theoretical G', theoreticalG, '   Recovered G', recoveredG)
    Producer_total_net_theoretical_G = sum(Producer_recovered_theoreticalG)
    Producer_total_net_recovered_G = sum(Producer_recoveredG)
    Producer_total_shrink = sum(Producer_shrink)
    
  
    return Producer_recoveredG, Producer_recovered_theoreticalG, Producer_total_net_theoretical_G, Producer_total_net_recovered_G, Producer_total_shrink

In [45]:
Producer_Recovery_Total(66)


([0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 0.0,
 0.0,
 array([0.]))

In [46]:
def Producer_Settled_G(meter):
    Producer_recovered_G = Producer_Recovery_Total(meter)[0]
#     Producer_total_net_recovered_G = sum(Producer_Recovery_Total(meter)[1])
    #print (Producer_recovered_G)
    Producer_NGL_POP = Coeff.loc[meter]['NGL_POP']
    #print (Producer_NGL_POP)
    Producer_settled_gallons = [Producer_recovered_G[i]*Producer_NGL_POP for i in range(len(Producer_recovered_G))]
    Producer_Settled_gallons_total = sum(Producer_settled_gallons)
    return Producer_NGL_POP,Producer_settled_gallons, Producer_Settled_gallons_total

In [47]:
Producer_Settled_G(66)

(1.0, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.0)

In [48]:
def Producer_NGL_market(meter):
    producer_fractions_NGL = ['C2', 'C3', 'IC4', 'NC4', 'C5']
    Producer_market_index = []
    price = []
    f_p_price = []
    tf = []
    for frac in producer_fractions_NGL:
        index = Coeff.loc[meter]['PROD_'+frac+'_MARKET']
       
        #print (index)
        Producer_market_index.append(index)
        #print (Producer_market_index)
        if index!= 0.0:
            p = Price[Price['INDEX'] == index]['PRICE'].values[0]
            #print (p)
            price.append(p)
            tf=(Coeff.loc[meter]['PRODUCER_'+str(frac)+'_TF'])
            fraction_producer_price = p + tf
            f_p_price.append(fraction_producer_price)
            ##print (frac, 'Price $', p,'    T&F', tf, '   NTP', fraction_producer_price )
        else:
            p = 0.0
            price.append(p)
            tf=(Coeff.loc[meter]['PRODUCER_'+str(frac)+'_TF'])
           
            fraction_producer_price = p + tf
            f_p_price.append(fraction_producer_price)
   
    
    return (f_p_price)

In [49]:
Coeff.loc[0]['PROD_'+'C2'+'_MARKET']
Producer_NGL_market(82)
#Coeff.loc[1166]['PRODUCER_'+str(frac)+'_TF'])

[0.159644, 0.510686, 0.667144, 0.667144, 0.8889]

In [50]:
def Producer_NGL_Revenue(meter):
    
    producer_NGL_net_recoveredG = list(Producer_Recovery_Total(meter)[0])
    producer_fractions_NGL = ['C2', 'C3', 'IC4', 'NC4', 'C5']
    
    C56 = producer_NGL_net_recoveredG[4]+producer_NGL_net_recoveredG[5]
    producer_NGL_net_recoveredG[4] = C56
    
    
    fraction_producer_price = Producer_NGL_market(meter)
    #print (fraction_producer_price)
    Producer_NGL_revenue_by_fraction = []
    Producer_total_settled_NGL_G = []
    NGL_POP = Coeff.loc[meter]['NGL_POP']
           
    for i in range(len(producer_fractions_NGL)):
        Producer_settled_NGL_G_by_fraction = producer_NGL_net_recoveredG[i]*NGL_POP
        Producer_total_settled_NGL_G.append(Producer_settled_NGL_G_by_fraction)
        Producer_NGL_revenue_by_fraction.append(fraction_producer_price[i]*Producer_settled_NGL_G_by_fraction)
    
    Producer_NGL_revenue = sum(Producer_NGL_revenue_by_fraction)

    return Producer_NGL_revenue, Producer_total_settled_NGL_G, sum(Producer_total_settled_NGL_G), fraction_producer_price, Producer_NGL_revenue_by_fraction, NGL_POP

In [51]:
Producer_NGL_Revenue(66)

(0.0,
 [0.0, 0.0, 0.0, 0.0, 0.0],
 0.0,
 [0.13854400000000003,
  0.4895860000000001,
  0.6460440000000001,
  0.6460440000000001,
  0.8678000000000001],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 1.0)

In [52]:
def Producer_Condensate_Revenue(meter):
    Producer_recoveredG = Producer_Recovery_Total(meter)[0]
    if Coeff.loc[meter]['RECOVERIES'] == 'FIXED':
        condensateG = Producer_recoveredG[4]+Producer_recoveredG[5]
        Producer_condensateG = condensateG*Coeff.loc[meter]['PRODUCER_CONDENSATE_PCT_RECOVERY']#.values[0]
        #print ('condensate G',condensateG)
        price = Coeff.loc[meter]['PRODUCER_COND_PRICE']#reference_price[reference_price['Index'] == 'NYMEX - Crude']['Price'].values[0]
        Producer_produced_condensate = Producer_condensateG/42.0
        Settled_producer_condensate = Producer_produced_condensate*Coeff.loc[meter]['COND_POP']
        #print(price)*print ('Producer condensate',Revenue_Producer_condensate)
        Revenue_Producer_condensate = price*Settled_producer_condensate
        
    else:
        route,b1,b2,b3,plant,gs,a = Asset_from_Routing(meter)
        condensateG = Producer_recoveredG[4]+Producer_recoveredG[5]
        #print (condensateG)
        Producer_condensateG = condensateG*Plant[Plant['PLANT'] == plant]['CONDENSATE_PCT_RECOVERY'].values[0]
        price = Coeff.loc[meter]['PRODUCER_COND_PRICE']#reference_price[reference_price['Index'] == 'NYMEX - Crude']['Price'].values[0]
        Producer_produced_condensate = Producer_condensateG/42.0
        Settled_producer_condensate = Producer_produced_condensate*Coeff.loc[meter]['COND_POP']
        Revenue_Producer_condensate = Settled_producer_condensate*price
    
    return Revenue_Producer_condensate, Producer_produced_condensate, Settled_producer_condensate, price, Coeff.loc[meter]['COND_POP']

In [53]:
Producer_Condensate_Revenue(67)

(0.0, 0.0, 0.0, 0, 0.0)

In [54]:
def Producer_res_index(meter):
    Prod_RES_index = []
    price = []
    Prod_RES_Index_pct = []
    for ind in range(3):
        index = Coeff.loc[meter]['PROD_RES_INDEX_'+str(ind+1)]
        #print(index)
        if index != 0.0 and len(index)>1:
            
            Prod_RES_index.append(index)
#             print()
#             print ('index',index)
            
           
            price.append(Price[Price['INDEX']==index]['PRICE'].values[0])
            #.values[0])
            
    
            pct = Coeff.loc[meter]['PROD_RES_INDEX_'+str(ind+1)+'_PCT']
       

            Prod_RES_Index_pct.append(pct)
          
            
    Prod_RES_deduct = Coeff.loc[meter]['PROD_RES_INDEX_DEDUCT']
    
    return (Prod_RES_index, price, Prod_RES_deduct, Prod_RES_Index_pct)



In [55]:
Producer_res_index(82)
#Coeff.loc[0]['TIPS_METER']

(['El Paso - Permian - IFGMR'], [2.27], -0.14, [0.995])

In [56]:
# def Prod_Plant_Fuel(meter):
#     plant = Asset_from_Routing(meter)[4]
#     if Coeff.loc[meter]['PLANT_FUEL'] == 'ACTUAL':
        
#         return Producer_Net_delivered_mmbtu(meter)*Plant[Plant['PLANT']==plant]['PLANT_FUEL_PCT_MMBTU'].values[0]
        
#     else:
#         return Producer_Net_delivered_mmbtu(meter)*Coeff.loc[meter]['PRODUCER_PLANT_FUEL_PCT']

def Prod_Plant_Fuel(meter):
    plant = Asset_from_Routing(meter)[4]
    if Coeff.loc[meter]['PLANT_FUEL'] == 'ACTUAL':
       
        return Plant[Plant['PLANT']==plant]['PLANT_FUEL_PCT_MMBTU'].values[0]
        
    else:
      
        return Coeff.loc[meter]['PRODUCER_PLANT_FUEL_PCT']
  

In [57]:
Prod_Plant_Fuel(67)


0.12

In [58]:
def Producer_RES_Revenue(meter):
    Shrink = Producer_Recovery_Total(meter)[4]
    plant_fuel = Prod_Plant_Fuel(meter)
    Plant_fuel_producer_mmbtu = Producer_Net_delivered_mmbtu(meter)* plant_fuel

    #print ('RES POP % ', Coeff.loc[meter]['RES_POP']*100)
    
    Producer_RES_AFS = (Producer_Net_delivered_mmbtu(meter)- Shrink -Plant_fuel_producer_mmbtu)
#     print ('Net_deklivered',Producer_Net_delivered_mmbtu(meter))
#     print ('srink', Shrink)
#     print ('Plant fuel', Plant_fuel_producer_mmbtu)
    Settled_RES_AFS = Producer_RES_AFS*Coeff.loc[meter]['RES_POP']
   
    
    INDEX, PRICE, DEDUCT, PCT = Producer_res_index(meter)
    
    
    total_Price = []

    for count in range(len(INDEX)):
      #  print (count)
       #print ('Index',count+1, ' $',PRICE[count]*100)
       #print ('Index ',count+1, ' %',PCT[count]*100)
       #print ('DEDUCT ',DEDUCT)
        total_Price.append(PRICE[count]*PCT[count])
    #print ('Index1, Index2 $ ', total_Price)
    
    
    #print ('Overall pct', Coeff.loc[meter]['Prod_Res_Overall_pct']*100)
    #print ('Overall deduct $', Coeff.loc[meter]['Prod_Res_Overall_deduct'])
    if coeff.loc[meter]['PROD_RES_OVERALL_PCT'] != 0.0:
        Producer_RES_PRICE  = (np.mean(total_Price)+DEDUCT)*Coeff.loc[meter]['PROD_RES_OVERALL_PCT'] + Coeff.loc[meter]['PROD_RES_OVERALL_DEDUCT']
    else:
        Producer_RES_PRICE  = np.mean(total_Price)+DEDUCT + Coeff.loc[meter]['PROD_RES_OVERALL_DEDUCT']
    
    #print ('Producer RES Price $',Producer_RES_PRICE)
    Revenue_Producer_RES = Producer_RES_PRICE*Settled_RES_AFS
#     print ('Revenue_Producer_RES',Revenue_Producer_RES)

    return Revenue_Producer_RES, Shrink, plant_fuel, Producer_RES_AFS,Settled_RES_AFS,Producer_RES_PRICE

In [59]:
Producer_RES_Revenue(67)


(array([0.]), array([0.]), 0.12, array([0.]), array([0.]), 1.8299999999999998)

In [60]:
def Producer_He_Revenue(meter):
    Producer_He_recovery, Producer_TheoreticalG, Producer_He_produced, shrink = Recovery_Producer(meter,'HE')
    #print ('He_recoveredG',Producer_He_produced)
    He_POP = Coeff.loc[meter]['HE_POP']
    Producer_He_price = Coeff.loc[meter]['HE_PRODUCER_USD']
    Producer_He_settled = Producer_He_produced*He_POP
    Producer_He_Revenue = Producer_He_settled*Producer_He_price


#     print ('Producer He Revenue ',Producer_He_Revenue)
#     print ()
    return Producer_He_Revenue,Producer_He_produced, Producer_He_settled, Producer_He_price, He_POP

In [61]:
Producer_He_Revenue(66)

(0.0, 0.0, 0.0, 0.0, 0)

In [62]:
def Producer_Revenue(meter):
    producer_revenue = Producer_NGL_Revenue(meter)[0]+Producer_RES_Revenue(meter)[0] + Producer_He_Revenue(meter)[0] + Producer_Condensate_Revenue(meter)[0]
    return producer_revenue

In [63]:
Producer_Revenue(66)

array([0.])

## Margin

In [64]:
def Margin(meter):
    margin = DCP_Revenue(meter)-Producer_Revenue(meter)
    return [margin[0]]
    

In [65]:
Margin(82)

C:\Users\ODmitriyeva\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.


[1783.0360022160112]

In [66]:
# Asset_from_Routing(175)
int(Coeff.loc[175]['ROUTE_NUMBER'])
# Converting_to_float(reference_routing)
# reference_routing[reference_routing['ROUTE_NUMBER'] == 53331]#['BOOSTER_NAME'].values[0]
reference_routing[reference_routing['ROUTE_NUMBER'] == 5331]['BOOSTER_NAME'].values

# len(reference_routing)
# reference_routing.ROUTE_NUMBER.values



array([], dtype=object)

In [67]:
def Variables(meter):
    variables =  [total_MCF(meter), total_MMBTU(meter),Fuel(meter), LU(meter),Net_delivered_mmbtu(meter),Net_delivered_mcf(meter),
                 DCP_NGL_Revenue(meter), DCP_NTP(meter), #1, 6recoveries, 6theoretical, 1 sum, 6 recovered, 1sum; 5prices, 5tf     
                 DCP_RES_Revenue(meter),DCP_RES_Price(meter),
                 DCP_Fees(meter), 
                 DCP_Condensate_Revenue(meter),DCP_He_Revenue(meter),Uplift_DCP(meter), DCP_Revenue(meter),
                      Fuel_producer(meter),LU_producer(meter), Producer_Net_delivered_mmbtu(meter),Producer_Net_delivered_mcf(meter),
                  Recovery_Producer(meter, 'C2')[0], Recovery_Producer(meter, 'C3')[0], Recovery_Producer(meter, 'IC4')[0], Recovery_Producer(meter, 'NC4')[0], Recovery_Producer(meter, 'C5')[0], Recovery_Producer(meter, 'C6')[0], Recovery_Producer(meter, 'HE')[0],
    Producer_NGL_Revenue(meter),Producer_Recovery_Total(meter)[0:4],Producer_RES_Revenue(meter),Coeff.loc[meter]['RES_POP'],Producer_Condensate_Revenue(meter), Producer_He_Revenue(meter), Producer_Revenue(meter), Margin(meter)] 
    
    massive = []
    new_element = []

    for element in variables:

        new_element.append(element)
    
    
    massive = []
    for element in new_element:
        if isinstance(element, tuple) or isinstance(element,list):

            for i in range(len(element)):
                if isinstance(element[i], list) or isinstance(element[i],tuple):
                    for k in range(len(element[i])):
                        massive.append(element[i][k])
                else:
                    massive.append(element[i])
        else:
            massive.append(element)
     
    list_variables = np.array(massive)
  
    return list_variables

In [68]:
len(Variables(1))

C:\Users\ODmitriyeva\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.


113

In [69]:
header_DCP = ['TIPS_METER','MCF', 'MMBTU', 'DCP_Field_Fuel','DCP_LU', 'ND_mmbtu', 'ND_mcf', 
          'DCP_NGL_Revenue', 
            'Recovery_pct_C2', 'Recovery_pct_C3','Recovery_pct_iC4','Recovery_pct_nC4','Recovery_pct_C5','Recovery_pct_C6',
       
          'DCP_Theoretical_C2','DCP_Theoretical_C3','DCP_Theoretical_iC4','DCP_Theoretical_nC4','DCP_Theoretical_C5','DCP_Theoretical_C6',
          'DCP_total_Theoretical_G',
          'DCP_Recovered_Gallons_C2', 'DCP_Recovered_Gallons_C3', 'DCP_Recovered_Gallons_iC4', 'DCP_Recovered_Gallons_nC4', 'DCP_Recovered_Gallons_C5', 'DCP_Recovered_Gallons_C6',
          'DCP_total_recovered_G', 
          'NGL_NTP_C2', 'NGL_NTP_C3', 'NGL_NTP_iC4', 'NGL_NTP_nC4', 'NGL_NTP_C5',
            'NGL_TF_C2','NGL_TF_C3','NGL_TF_iC4','NGL_TF_nC4','NGL_TF_C5',
              
              
          'DCP_RES_Revenue', 'DCP_Shrink', 'DCP_plant_fuel','DCP_RES_AFS', 'DCP_RES_Price',
          'Fees', 
          'DCP_Condensate_Revenue', 'DCP_Produced_Condensate', 'DCP_Condensate_Price',
          'DCP_He_Revenue', 'DCP_He_Production', 'DCP_He_Price',
          'DCP_Uplift',
          'DCP_Revenue']

header_producer = ['Producer_Field_Fuel','Producer_LU','Producer_ND_mmbtu', 'Producer_ND_mcf', 
             'Producer_Recovery_C2','Producer_Recovery_C3','Producer_Recovery_iC4','Producer_Recovery_nC4','Producer_Recovery_C5','Producer_Recovery_C6','Producer_Recovery_He',
              'Producer_NGL_Revenue',
            'Producer_Settled_C2','Producer_Settled_C3','Producer_Settled_iC4','Producer_Settled_nC4','Producer_Settled_C5',
          'Producer_Settled_G', 
                   'Producer_NGL_NTP_C2', 'Producer_NGL_NTP_C3', 'Producer_NGL_NTP_iC4', 'Producer_NGL_NTP_nC4', 'Producer_NGL_NTP_C5',
           'Producer_NGL_Revenue_C2','Producer_NGL_Revenue_C3','Producer_NGL_Revenue_iC4','Producer_NGL_Revenue_nC4','Producer_NGL_Revenue_C56',        
            'NGL_POP',
             'Producer_Recovered_C2','Producer_Recovered_C3','Producer_Recovered_iC4','Producer_Recovered_nC4','Producer_Recovered_C5','Producer_Recovered_C6',      
            'Producer_Theoretical_C2','Producer_Theoretical_C3','Producer_Theoretical_iC4','Producer_Theoretical_nC4','Producer_Theoretical_C5','Producer_Theoretical_C6',
          'Producer_Theoretical_total','Producer_Recovered_total', 
                   
          
    
        
                   
                   'Producer_RES_Revenue','Producer_Shrink', 'Producer_plant_fuel','Producer_Res_AFS','Producer_Settled_allocated', 'Producer_RES_price','Producer_RES_POP',
                   
                    'Producer_Condensate_Revenue', 'Producer_Produced_Condensate', 'Producer_Settled_Condensate','Producer_Condensate_Price','Condensate_POP',
                   'Producer_He_Revenue', 'Producer_He_Production','Producer_Settled_He', 'Producer_He_Price', 'He_POP', 'Producer_Revenue', 'Margin']

header = header_DCP+header_producer
print (len(header))
header_error = ['error' for i in range(len(header))]

114


In [70]:
len(Coeff['TIPS_METER'])

3760

In [71]:
import time
t0= time.clock()
i=0
j=0
meters_fall_out = []
a = {}
for meter in tqdm(range(len(Coeff['TIPS_METER']))):
    try:
       
#         print ('good meter', i)
        tag = Coeff.loc[meter]['TIPS_METER']
        rec_dcp_dict = {}
        rec_prod_dict = {}
        b = Variables(meter)
    
        
                              
        a[tag] = b
        i = i+1
    except:
        j = j+1
#         print('bad meter', j)
        meters_fall_out.append(Coeff.loc[meter]['TIPS_METER'])

df2 = pd.DataFrame(a).transpose()
df2 = df2.reset_index()

df2.columns = header
print (df2.head())

#df1.to_csv('Test_table_DCP-Producer_Jan2019_1390.csv')

t1 = time.clock() - t0
print("Time elapsed (min): ", t1/60.) # CPU seconds elapsed (floating point)

C:\Users\ODmitriyeva\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  
100%|██████████████████████████████████████████████████████████████████████████████| 3760/3760 [42:24<00:00,  2.09it/s]


  TIPS_METER     MCF   MMBTU  DCP_Field_Fuel  DCP_LU  ND_mmbtu   ND_mcf  \
0   38173565  5300.0  5379.0            0.02    0.09   4787.31  4717.00   
1  718625-00  1405.0  1695.0            0.02    0.09   1508.55  1250.45   
2   13135010     0.0     0.0            0.02    0.09      0.00     0.00   
3   94059-00     0.0     0.0            0.02    0.09      0.00     0.00   
4  720147-00   639.0   730.0            0.02    0.09    649.70   568.71   

   DCP_NGL_Revenue  Recovery_pct_C2  Recovery_pct_C3     ...       \
0       726.607224         0.725410         0.985782     ...        
1      1961.749234         0.725410         0.985782     ...        
2         0.000000         0.660624         0.979000     ...        
3         0.000000         0.660624         0.979000     ...        
4       694.331316         0.801860         0.990131     ...        

   Producer_Settled_Condensate  Producer_Condensate_Price  Condensate_POP  \
0                          0.0                        0.0

C:\Users\ODmitriyeva\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:33: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead


Time elapsed (min):  42.409414540616666


In [72]:
print (len(meters_fall_out))


0


In [73]:
#df1 = df1.drop('level_0', 1)
#df2.columns = header
df2.head()

TIPS_METER     MCF   MMBTU  DCP_Field_Fuel  DCP_LU  ND_mmbtu   ND_mcf  \
0   38173565  5300.0  5379.0            0.02    0.09   4787.31  4717.00   
1  718625-00  1405.0  1695.0            0.02    0.09   1508.55  1250.45   
2   13135010     0.0     0.0            0.02    0.09      0.00     0.00   
3   94059-00     0.0     0.0            0.02    0.09      0.00     0.00   
4  720147-00   639.0   730.0            0.02    0.09    649.70   568.71   

   DCP_NGL_Revenue  Recovery_pct_C2  Recovery_pct_C3     ...       \
0       726.607224         0.725410         0.985782     ...        
1      1961.749234         0.725410         0.985782     ...        
2         0.000000         0.660624         0.979000     ...        
3         0.000000         0.660624         0.979000     ...        
4       694.331316         0.801860         0.990131     ...        

   Producer_Settled_Condensate  Producer_Condensate_Price  Condensate_POP  \
0                          0.0                        0.0             0.0   
1                          0.0                        0.0             0.0   
2                          0.0                        0.0             0.0   
3                          0.0                        0.0             0.0   
4                          0.0                        0.0             0.0   

   Producer_He_Revenue  Producer_He_Production  Producer_Settled_He  \
0                  0.0                     0.0                  0.0   
1                  0.0                     0.0                  0.0   
2                  0.0                     0.0                  0.0   
3                  0.0                     0.0                  0.0   
4                  0.0                     0.0                  0.0   

   Producer_He_Price  He_POP  Producer_Revenue       Margin  
0                0.0     0.0       8578.852138  3300.215340  
1                0.0     0.0       2041.963864  2703.761201  
2                0.0     0.0          0.000000   500.000000  
3                0.0     0.0          0.000000   500.000000  
4                0.0     0.0       1417.041782  1145.744459  

[5 rows x 114 columns]

## OPEX

In [74]:
Opex.head()
# Coeff = Coeff[0:50]


DATE        REGION               AREA  \
0  1546300800000000000       Permian               SENM   
1  1546300800000000000  Midcontinent          Panhandle   
2  1546300800000000000  Midcontinent  Southern Oklahoma   
3  1546300800000000000  Midcontinent   Central Oklahoma   
4  1546300800000000000  Midcontinent            Liberal   

                  RC_CODE ALLOCATION_NAME ALLOCATION_TYPE OPEX_TYPE  \
0        529 Booster_F484             529         Booster     Plant   
1             3-T Pb_G428             3-T         Booster     Field   
2            AC West_G452         AC West         Booster     Plant   
3  Alabaster Booster_G877       Alabaster         Booster     Field   
4           Albright_L015        Albright         Booster     Field   

   LABOR_AND_BENEFITS  MATERIALS_AND_SUPPLIES  CHEMICAL_AND_LUBE_PURCHASES  \
0            79333.81                47243.89                     24366.60   
1            42010.61                75313.16                     22395.87   
2            70613.49                49612.94                         0.00   
3                0.00                    0.00                         0.00   
4             2967.65                    0.00                         0.00   

             ...              ACCOUNTING_ACCRUALS  OVERHAUL_BREAKDOWN  \
0            ...                             0.00                 0.0   
1            ...                             0.00                 0.0   
2            ...                             0.00                 0.0   
3            ...                           304.51                 0.0   
4            ...                             0.00                 0.0   

   OVERHAUL_CONDITION_BASED  TURNAROUND_TURNARO  PSV_TESTING  \
0                  25989.25                 0.0      1452.96   
1                   1029.00                 0.0         0.00   
2                      0.00                 0.0         0.00   
3                      0.00                 0.0         0.00   
4                      0.00                 0.0         0.00   

   MECHANICAL_INTEGRITY_INSPECT   LU  PIPE_INTEGRITY_COMPLIANCE  \
0                      51649.75  0.0                        0.0   
1                          0.00  0.0                        0.0   
2                          0.00  0.0                        0.0   
3                          0.00  0.0                        0.0   
4                          0.00  0.0                        0.0   

   CP_CORROSION_PROGRAM  CORPORATE_ENTRIES_MANAGED  
0                   0.0                  25066.094  
1                   0.0                  31388.337  
2                   0.0                 347215.500  
3                   0.0                    110.000  
4                   0.0                     55.000  

[5 rows x 29 columns]

In [75]:
def check_routing(number_row):
    r = Route.loc[number_row]['ROUTE_NUMBER']
    b1 = Route.loc[number_row]['BOOSTER_NAME']
    b2 = Route.loc[number_row]['SECONDARY_BOOSTER']
    b3 = Route.loc[number_row]['TERTIARY_BOOSTER']
    p = Route.loc[number_row]['PLANT_NAME']
    gs = Route.loc[number_row]['GATHERING_SYSTEM']
    a = Route.loc[number_row]['AREA']
    return [r,b1,b2,b3,p,gs,a]
  

  ### Return table which consists of all the meters and their MCF that belong to given route

def virtual_meter_table(route):
    v_m = Coeff[Coeff['ROUTE_NUMBER'] == route][['TIPS_METER','MCF','ROUTE_NUMBER']]
    v_m.MCF = v_m.MCF.astype('int64', copy=False)
    return v_m
  
def Opex_Total(df):
    Total_Base_list = ['LABOR_AND_BENEFITS', 'MATERIALS_AND_SUPPLIES' , 'CHEMICAL_AND_LUBE_PURCHASES', 
                   'IT_PURCHASES', 'EMPLOYEE_EXPENSES', 'TRANSPORTATION', 'CONTRACT_SERVICES' , 
                   'LEASE_EXPENSE','UTILITIES', 'FEES_AND_OTHER_COSTS' , 'INSURANCE', 'TAXES', 
                   'ACCOUNTING_ACCRUALS']
    Total_Reliability_list = ['OVERHAUL_BREAKDOWN','OVERHAUL_CONDITION_BASED','TURNAROUND_TURNARO',
                          'PSV_TESTING','MECHANICAL_INTEGRITY_INSPECT']
    Total_Pipeline_Integrity_list = ['LU', 'PIPE_INTEGRITY_COMPLIANCE' ,'CP_CORROSION_PROGRAM']

    df['Total_Base'] = df[Total_Base_list].sum(axis=1)
    df['Total_Reliability'] =df[Total_Reliability_list].sum(axis=1)
    df['Total_Pipeline_Integrity'] = df[Total_Pipeline_Integrity_list].sum(axis=1)

    Total_list = ['Total_Base','Total_Reliability', 'Total_Pipeline_Integrity', 'CORPORATE_ENTRIES_MANAGED']
    df['Total'] = df[Total_list].sum(axis = 1)
    df.Total = df.Total.astype('int64', copy=False)
    return df

def opex_asset(allocation_name, df, categories):
    ## find all routs where allocation name is found
    
    a_type = df[df['ALLOCATION_NAME'] == allocation_name]['ALLOCATION_TYPE'].values[0]
    a_total =  df[df['ALLOCATION_NAME'] == allocation_name][categories].values[0]
    a_total = a_total.astype('int64', copy=False)
    Temp = pd.DataFrame()
    for i in range(len(Route.ROUTE_NUMBER)):
        
        if allocation_name in check_routing(i):
 
            #find all meters that belong to this route and contain the allocation name
            #get $total of this allocation_name
            
            #get the table for all meter associated with this allocation_name
            temp_table = virtual_meter_table(check_routing(i)[0]).reset_index(drop = 'True')   
            
             #Assign "Allocation_name"
            temp_table['Allocation_name']=allocation_name
            
            #Assign route number
            temp_table['route'] = check_routing(i)[0] 
            
            
            #append the table
            
            Temp = Temp.append(temp_table, ignore_index = True, sort=False)
            
            #route_in_coeff = check_routing(i)[0] in coeff
    
    #Temp[a_type+'_opex'] = Temp.MCF/Temp.MCF.sum()*a_total
    if len(Temp) >0:
    #Getting an Opex load split between meters based on their MCF contribution%
        for k in range(len(categories)):
            Temp[categories[k]+'_opex'] = Temp.MCF/Temp.MCF.sum()*a_total[k]
        
        Temp[a_type+'_opex'] = Temp.MCF/Temp.MCF.sum()*df[df['ALLOCATION_NAME'] == allocation_name]['Total'].values[0]
        return Temp

In [76]:
opex = Opex.groupby(['ALLOCATION_NAME', 'ALLOCATION_TYPE']).sum().reset_index()
opex = Opex_Total(opex)
opex.head()

ALLOCATION_NAME ALLOCATION_TYPE  \
0                                               3-T         Booster   
1                                               529         Booster   
2  715_Coastal_Elliff_Ingram_Wardner_West Wardner 3         Booster   
3                                           AC West         Booster   
4                                         Alabaster         Booster   

           DATE  LABOR_AND_BENEFITS  MATERIALS_AND_SUPPLIES  \
0  1.546301e+18            42010.61                75313.16   
1  1.546301e+18            79333.81                47243.89   
2  3.092602e+18                0.00                    0.00   
3  1.546301e+18            70613.49                49612.94   
4  1.546301e+18                0.00                    0.00   

   CHEMICAL_AND_LUBE_PURCHASES  IT_PURCHASES  EMPLOYEE_EXPENSES  \
0                     22395.87          0.00             640.68   
1                     24366.60       8753.51             337.11   
2                         0.00          0.00               0.00   
3                         0.00      20094.02            1224.57   
4                         0.00          0.00               0.00   

   TRANSPORTATION  CONTRACT_SERVICES   ...    PSV_TESTING  \
0         3082.23            8760.46   ...           0.00   
1         1621.50           59001.27   ...        1452.96   
2            0.00               0.00   ...           0.00   
3           14.00            2204.80   ...           0.00   
4            0.00               0.00   ...           0.00   

   MECHANICAL_INTEGRITY_INSPECT   LU  PIPE_INTEGRITY_COMPLIANCE  \
0                          0.00  0.0                        0.0   
1                      51649.75  0.0                        0.0   
2                          0.00  0.0                        0.0   
3                          0.00  0.0                        0.0   
4                          0.00  0.0                        0.0   

   CP_CORROSION_PROGRAM  CORPORATE_ENTRIES_MANAGED  Total_Base  \
0                   0.0                  31388.337   175031.13   
1                   0.0                  25066.094   459887.60   
2                   0.0                      0.000     9781.83   
3                   0.0                 347215.500   144529.57   
4                   0.0                    110.000      304.51   

   Total_Reliability  Total_Pipeline_Integrity   Total  
0            1029.00                       0.0  207448  
1           79091.96                       0.0  564045  
2               0.00                       0.0    9781  
3               0.00                       0.0  491745  
4               0.00                       0.0     414  

[5 rows x 29 columns]

In [77]:
columns = list(opex.columns)
categories  = columns[3:len(columns)]
#print (categories)

opexDF = pd.DataFrame()

for line in tqdm(opex['ALLOCATION_NAME']):
    opexDF = opexDF.append(opex_asset(line, opex, categories), ignore_index = True, sort=False)

100%|████████████████████████████████████████████████████████████████████████████████| 357/357 [06:18<00:00,  1.17s/it]


In [78]:
opexDF = opexDF.drop(['MCF','ROUTE_NUMBER'], 1)
opexDF = opexDF.groupby(['TIPS_METER']).sum().reset_index()
len(opexDF.TIPS_METER)
opexDF.head()

TIPS_METER   route  LABOR_AND_BENEFITS_opex  MATERIALS_AND_SUPPLIES_opex  \
0   014276ST  102582                 6.493245                     2.430161   
1   014277ST  102582                 4.452511                     1.666396   
2   014278ST  102582                 5.009074                     1.874696   
3   014279ST  102582                 5.472878                     2.048279   
4   014280ST  102582                 6.957048                     2.603744   

   CHEMICAL_AND_LUBE_PURCHASES_opex  IT_PURCHASES_opex  \
0                          1.919627                0.0   
1                          1.316316                0.0   
2                          1.480855                0.0   
3                          1.617972                0.0   
4                          2.056744                0.0   

   EMPLOYEE_EXPENSES_opex  TRANSPORTATION_opex  CONTRACT_SERVICES_opex  \
0                0.078899             0.300654                3.047715   
1                0.054102             0.206163                2.089862   
2                0.060865             0.231933                2.351094   
3                0.066500             0.253408                2.568788   
4                0.084534             0.322129                3.265409   

   LEASE_EXPENSE_opex    ...      PIPE_INTEGRITY_COMPLIANCE_opex  \
0            0.124754    ...                                 0.0   
1            0.085546    ...                                 0.0   
2            0.096239    ...                                 0.0   
3            0.105150    ...                                 0.0   
4            0.133665    ...                                 0.0   

   CP_CORROSION_PROGRAM_opex  CORPORATE_ENTRIES_MANAGED_opex  Total_Base_opex  \
0                   0.189222                        1.750716        16.390351   
1                   0.129752                        1.200491        11.239098   
2                   0.145971                        1.350552        12.643985   
3                   0.159487                        1.475603        13.814725   
4                   0.202738                        1.875767        17.561091   

   Total_Reliability_opex  Total_Pipeline_Integrity_opex  Total_opex  \
0                0.176170                       0.379507   18.696751   
1                0.120802                       0.260233   12.820629   
2                0.135902                       0.292762   14.423208   
3                0.148486                       0.319870   15.758690   
4                0.188753                       0.406615   20.032233   

   Plant_opex  Booster_opex  Area_opex  
0    0.001590           0.0  18.695161  
1    0.001090           0.0  12.819539  
2    0.001226           0.0  14.421981  
3    0.001340           0.0  15.757350  
4    0.001703           0.0  20.030530  

[5 rows x 31 columns]

In [79]:
# output = pd.merge(df_margin, opexDF, on='TIPS_METER', how='inner')
output = pd.merge(df2, opexDF, on='TIPS_METER', how='inner')
# for column in output.columns:
#     print(column)

In [80]:
df2.to_csv('output/SENM/SENM-Margin-Jan.csv')
output.to_csv('output/SENM/SENM-Margin-OPEX-Jan.csv')
opexDF.to_csv('output/SENM/SENM-OPEX-Jan.csv')

## UI Transformation Calcs

In [81]:
df1 = output

In [82]:
df1['CNTR_LEVERAGE_RESIDUE_USD'] = df1.Producer_Res_AFS*(1-df1.Producer_RES_POP)*df1.DCP_RES_Price



df1['LEVERAGE_CONDENSATE_USD'] = (df1.DCP_Produced_Condensate-df1.Producer_Settled_Condensate)*df1.DCP_Condensate_Price

df1['LEVERAGE_HELIUM_USD'] = (df1.DCP_He_Production-df1.Producer_Settled_He)*df1.DCP_He_Price

df1['LEVERAGE_FEE_USD'] = df1.Fees
df1['LEVERAGE_RESIDUE_PRICE']= (df1.DCP_RES_Price - df1.Producer_RES_price)*df1.Producer_Settled_allocated
df1['LEVERAGE_TF_PRICE'] = df1.Producer_Settled_C2*df1.NGL_NTP_C2- df1.Producer_NGL_Revenue_C2 + df1.Producer_Settled_C3*df1.NGL_NTP_C3 - df1.Producer_NGL_Revenue_C3 +df1.Producer_Settled_iC4*df1.NGL_NTP_iC4 - df1.Producer_NGL_Revenue_iC4 + df1.Producer_Settled_nC4*df1.NGL_NTP_nC4 - df1.Producer_NGL_Revenue_nC4+df1.Producer_Settled_C5*df1.NGL_NTP_C5-  df1.Producer_NGL_Revenue_C56

df1['LEVERAGE_HELIUM_PRICE'] = (df1.DCP_He_Price-df1.Producer_He_Price)*df1.Producer_Settled_He

df1['LEVERAGE_CONDENSATE_PRICE'] = (df1.DCP_Condensate_Price -df1.Producer_Condensate_Price)*df1.Producer_Settled_Condensate

df1['LEVERAGE_UPLIFT'] = df1.DCP_Uplift
df1['DIRECT_COST'] = df1.Booster_opex

df1['OP_LEVERAGE_C5_RECOVERY'] = (df1.Producer_Theoretical_C5+df1.Producer_Theoretical_C6)*(df1.Recovery_pct_C5-df1.Producer_Recovery_C5)*df1.NGL_POP*(df1.NGL_NTP_C5 +(df1.NGL_NTP_C5-df1.Producer_NGL_NTP_C5))

df1['OP_LEVERAGE_NC4_RECOVERY'] = df1.Producer_Theoretical_nC4*(df1.Recovery_pct_nC4-df1.Producer_Recovery_nC4)*df1.NGL_POP*(df1.NGL_NTP_nC4+(df1.NGL_NTP_nC4-df1.Producer_NGL_NTP_nC4))

df1['OP_LEVERAGE_IC4_RECOVERY'] = df1.Producer_Theoretical_iC4*(df1.Recovery_pct_iC4-df1.Producer_Recovery_iC4)*df1.NGL_POP*(df1.NGL_NTP_iC4+(df1.NGL_NTP_iC4-df1.Producer_NGL_NTP_iC4))

df1['OP_LEVERAGE_C3_RECOVERY'] = df1.Producer_Theoretical_C3*(df1.Recovery_pct_C3-df1.Producer_Recovery_C3)*df1.NGL_POP*(df1.NGL_NTP_C3+(df1.NGL_NTP_C3-df1.Producer_NGL_NTP_C3))

df1['OP_LEVERAGE_C2_RECOVERY'] = df1.Producer_Theoretical_C2*(df1.Recovery_pct_C2-df1.Producer_Recovery_C2)*df1.NGL_POP*(df1.NGL_NTP_C2+(df1.NGL_NTP_C2-df1.Producer_NGL_NTP_C2))

df1['OP_LEVERAGE_FIELD_FUEL'] = (df1.Producer_Field_Fuel*df1.Producer_ND_mmbtu - df1.DCP_Field_Fuel*df1.ND_mmbtu)*df1.DCP_RES_Price

df1['OP_LEVERAGE_PLANT_FUEL'] = (df1.Producer_plant_fuel * df1.Producer_ND_mmbtu - df1.DCP_plant_fuel*df1.ND_mmbtu)*df1.DCP_RES_Price

df1['OP_LEVERAGE_SHRINK_FUEL'] = (df1.Producer_Shrink-df1.DCP_Shrink)*df1.DCP_RES_Price

df1['OP_LEVERAGE_LU_FUEL'] = df1.MMBTU*(df1.Producer_LU-df1.DCP_LU)*df1.DCP_RES_Price
df1['LEVERAGE_NGL_USD'] = df1.DCP_NGL_Revenue- df1.Producer_NGL_Revenue-df1.LEVERAGE_TF_PRICE-(df1.OP_LEVERAGE_C5_RECOVERY+df1.OP_LEVERAGE_NC4_RECOVERY+df1.OP_LEVERAGE_IC4_RECOVERY+df1.OP_LEVERAGE_C3_RECOVERY+df1.OP_LEVERAGE_C2_RECOVERY)


df1['WH_MM_CFD'] = df1.MCF/pd.to_datetime(date1).days_in_month
df1['EBITDA'] = df1.Margin- df1.Total_opex
df1['DATE'] = date1
# df1.columns


In [83]:
df1.to_csv('output/SENM/SENM-Margin-OPEX-UI-Jan2019.csv')

In [84]:
df1.head()


TIPS_METER     MCF   MMBTU  DCP_Field_Fuel  DCP_LU  ND_mmbtu   ND_mcf  \
0   38173565  5300.0  5379.0            0.02    0.09   4787.31  4717.00   
1  718625-00  1405.0  1695.0            0.02    0.09   1508.55  1250.45   
2   13135010     0.0     0.0            0.02    0.09      0.00     0.00   
3   94059-00     0.0     0.0            0.02    0.09      0.00     0.00   
4  720147-00   639.0   730.0            0.02    0.09    649.70   568.71   

   DCP_NGL_Revenue  Recovery_pct_C2  Recovery_pct_C3         ...           \
0       726.607224         0.725410         0.985782         ...            
1      1961.749234         0.725410         0.985782         ...            
2         0.000000         0.660624         0.979000         ...            
3         0.000000         0.660624         0.979000         ...            
4       694.331316         0.801860         0.990131         ...            

   OP_LEVERAGE_C3_RECOVERY  OP_LEVERAGE_C2_RECOVERY  OP_LEVERAGE_FIELD_FUEL  \
0                 0.000000                 0.000000                 0.00000   
1                 0.000000                 0.000000                 0.00000   
2                 0.000000                -0.000000                 0.00000   
3                 0.000000                -0.000000                 0.00000   
4                18.224107                12.004543                69.74858   

   OP_LEVERAGE_PLANT_FUEL  OP_LEVERAGE_SHRINK_FUEL  OP_LEVERAGE_LU_FUEL  \
0                 0.00000                 0.000000                0.000   
1                 0.00000                 0.000000                0.000   
2                 0.00000                 0.000000               -0.000   
3                 0.00000                 0.000000               -0.000   
4                16.66298               -48.647838             -132.714   

   LEVERAGE_NGL_USD   WH_MM_CFD       EBITDA                 DATE  
0        726.607224  170.967742  1884.604220  2019-01-01 00:00:00  
1       1961.749234   45.322581  2328.490705  2019-01-01 00:00:00  
2          0.000000    0.000000   500.000000  2019-01-01 00:00:00  
3          0.000000    0.000000   500.000000  2019-01-01 00:00:00  
4        136.608546   20.612903   974.665811  2019-01-01 00:00:00  

[5 rows x 167 columns]

In [85]:
def Margin_calcs():
    i=0
    j=0
    meters_fall_out = []
    a = {}
    for meter in tqdm(range(len(Coeff['TIPS_METER']))):
        try:
       
#         print ('good meter', i)
            tag = Coeff.loc[meter]['TIPS_METER']
            rec_dcp_dict = {}
            rec_prod_dict = {}
            b = Variables(meter)
    
        
                              
            a[tag] = b
            i = i+1
        except:
            j = j+1
#         print('bad meter', j)
            meters_fall_out.append(Coeff.loc[meter]['TIPS_METER'])

    df2 = pd.DataFrame(a).transpose()
    df2 = df2.reset_index()

    df2.columns = header
    return df2

In [86]:
def Opex_calcs():
    opex = Opex.groupby(['ALLOCATION_NAME', 'ALLOCATION_TYPE']).sum().reset_index()
    opex = Opex_Total(opex)
    columns = list(opex.columns)
    categories  = columns[3:len(columns)]
    #print (categories)

    opexDF = pd.DataFrame()

    for line in tqdm(opex['ALLOCATION_NAME']):
        opexDF = opexDF.append(opex_asset(line, opex, categories), ignore_index = True, sort=False)
    opexDF = opexDF.drop(['MCF','ROUTE_NUMBER'], 1)
    opexDF = opexDF.groupby(['TIPS_METER']).sum().reset_index()
    return opexDF

In [87]:
def UI_calcs(df1):
    df1['CNTR_LEVERAGE_RESIDUE_USD'] = df1.Producer_Res_AFS*(1-df1.Producer_RES_POP)*df1.DCP_RES_Price



    df1['LEVERAGE_CONDENSATE_USD'] = (df1.DCP_Produced_Condensate-df1.Producer_Settled_Condensate)*df1.DCP_Condensate_Price

    df1['LEVERAGE_HELIUM_USD'] = (df1.DCP_He_Production-df1.Producer_Settled_He)*df1.DCP_He_Price

    df1['LEVERAGE_FEE_USD'] = df1.Fees
    df1['LEVERAGE_RESIDUE_PRICE']= (df1.DCP_RES_Price - df1.Producer_RES_price)*df1.Producer_Settled_allocated
    df1['LEVERAGE_TF_PRICE'] = df1.Producer_Settled_C2*df1.NGL_NTP_C2- df1.Producer_NGL_Revenue_C2 + df1.Producer_Settled_C3*df1.NGL_NTP_C3 - df1.Producer_NGL_Revenue_C3 +df1.Producer_Settled_iC4*df1.NGL_NTP_iC4 - df1.Producer_NGL_Revenue_iC4 + df1.Producer_Settled_nC4*df1.NGL_NTP_nC4 - df1.Producer_NGL_Revenue_nC4+df1.Producer_Settled_C5*df1.NGL_NTP_C5-  df1.Producer_NGL_Revenue_C56

    df1['LEVERAGE_HELIUM_PRICE'] = (df1.DCP_He_Price-df1.Producer_He_Price)*df1.Producer_Settled_He

    df1['LEVERAGE_CONDENSATE_PRICE'] = (df1.DCP_Condensate_Price -df1.Producer_Condensate_Price)*df1.Producer_Settled_Condensate

    df1['LEVERAGE_UPLIFT'] = df1.DCP_Uplift
    df1['DIRECT_COST'] = df1.Booster_opex

    df1['OP_LEVERAGE_C5_RECOVERY'] = (df1.Producer_Theoretical_C5+df1.Producer_Theoretical_C6)*(df1.Recovery_pct_C5-df1.Producer_Recovery_C5)*df1.NGL_POP*(df1.NGL_NTP_C5 +(df1.NGL_NTP_C5-df1.Producer_NGL_NTP_C5))

    df1['OP_LEVERAGE_NC4_RECOVERY'] = df1.Producer_Theoretical_nC4*(df1.Recovery_pct_nC4-df1.Producer_Recovery_nC4)*df1.NGL_POP*(df1.NGL_NTP_nC4+(df1.NGL_NTP_nC4-df1.Producer_NGL_NTP_nC4))

    df1['OP_LEVERAGE_IC4_RECOVERY'] = df1.Producer_Theoretical_iC4*(df1.Recovery_pct_iC4-df1.Producer_Recovery_iC4)*df1.NGL_POP*(df1.NGL_NTP_iC4+(df1.NGL_NTP_iC4-df1.Producer_NGL_NTP_iC4))

    df1['OP_LEVERAGE_C3_RECOVERY'] = df1.Producer_Theoretical_C3*(df1.Recovery_pct_C3-df1.Producer_Recovery_C3)*df1.NGL_POP*(df1.NGL_NTP_C3+(df1.NGL_NTP_C3-df1.Producer_NGL_NTP_C3))

    df1['OP_LEVERAGE_C2_RECOVERY'] = df1.Producer_Theoretical_C2*(df1.Recovery_pct_C2-df1.Producer_Recovery_C2)*df1.NGL_POP*(df1.NGL_NTP_C2+(df1.NGL_NTP_C2-df1.Producer_NGL_NTP_C2))

    df1['OP_LEVERAGE_FIELD_FUEL'] = (df1.Producer_Field_Fuel*df1.Producer_ND_mmbtu - df1.DCP_Field_Fuel*df1.ND_mmbtu)*df1.DCP_RES_Price

    df1['OP_LEVERAGE_PLANT_FUEL'] = (df1.Producer_plant_fuel * df1.Producer_ND_mmbtu - df1.DCP_plant_fuel*df1.ND_mmbtu)*df1.DCP_RES_Price

    df1['OP_LEVERAGE_SHRINK_FUEL'] = (df1.Producer_Shrink-df1.DCP_Shrink)*df1.DCP_RES_Price

    df1['OP_LEVERAGE_LU_FUEL'] = df1.MMBTU*(df1.Producer_LU-df1.DCP_LU)*df1.DCP_RES_Price
    df1['LEVERAGE_NGL_USD'] = df1.DCP_NGL_Revenue- df1.Producer_NGL_Revenue-df1.LEVERAGE_TF_PRICE-(df1.OP_LEVERAGE_C5_RECOVERY+df1.OP_LEVERAGE_NC4_RECOVERY+df1.OP_LEVERAGE_IC4_RECOVERY+df1.OP_LEVERAGE_C3_RECOVERY+df1.OP_LEVERAGE_C2_RECOVERY)


    df1['WH_MM_CFD'] = df1.MCF/pd.to_datetime(date1).days_in_month
    df1['EBITDA'] = df1.Margin- df1.Total_opex
    df1['DATE'] = date
    return df1
    

In [88]:
def Assign_date(date1):
    Coeff = coeff[coeff['DATE'] == date1].reset_index(drop = True)
    Price = reference_price[reference_price['DATE'] == date1].reset_index(drop = True)
    Plant = reference_plant[reference_plant['DATE'] == date1].reset_index(drop = True)
    Booster = reference_booster[reference_booster['DATE'] == date1].reset_index(drop = True)
    Route = reference_routing[reference_routing['DATE'] == date1].reset_index(drop = True)
    Opex = reference_opex[reference_opex['DATE'] == date1].reset_index(drop = True)
    Static = reference_static
    return Coeff, Price, Plant, Booster, Route, Opex, Static

In [89]:
months = ['Aug2018', 'Sept2018', 'Oct2018', 'Nov2108', 'Dec2018', 'Jan2019']
dates = [ '2018-08-01 00:00:00', '2018-09-01 00:00:00', '2018-10-01 00:00:00', '2018-11-01 00:00:00', '2018-12-01 00:00:00', '2019-01-01 00:00:00']

In [92]:
area = 'Southern Oklahoma'
i=0
for date in dates:
    print (date)
    Coeff, Price, Plant, Booster, Route, Opex, Static = Assign_date(date)
    Converting_to_float(Coeff)
    Converting_to_float(Booster)
    Converting_to_float(Price)
    Converting_to_float(Route)
    Converting_to_float(Opex)
    Converting_to_float(Static)
    Converting_to_float(Plant)
    Coeff = Coeff[Coeff.AREA == area].reset_index(drop = True)
    df_margin = Margin_calcs()
    df_opex = Opex_calcs()
    df_margin_opex = pd.merge(df_margin, df_opex, on='TIPS_METER', how='inner')
    df_margin_opex_ui = UI_calcs(df_margin_opex)
    
    file_name = 'output/Southern_Oklahoma/Southern_Oklahoma-Margin-OPEX-UI-'+str(months[i])+'.csv'
    
    df_margin.to_csv('output/Southern_Oklahoma/Southern_Oklahoma-Margin-'+str(months[i])+'.csv')
    df_margin_opex.to_csv('output/Southern_Oklahoma/Southern_Oklahoma-Margin-OPEX-'+str(months[i])+'.csv')
    df_opex.to_csv('output/Southern_Oklahoma/Southern_Oklahoma-OPEX-'+str(months[i])+'.csv')
    
    df_margin_opex_ui.to_csv(file_name)
    i= i+1
    
    

    
    
    

2018-08-01 00:00:00


100%|████████████████████████████████████████████████████████████████████████████████| 359/359 [06:19<00:00,  1.03it/s]


2018-09-01 00:00:00


100%|████████████████████████████████████████████████████████████████████████████████| 359/359 [05:53<00:00,  1.05it/s]


2018-10-01 00:00:00


100%|████████████████████████████████████████████████████████████████████████████████| 359/359 [05:50<00:00,  1.04it/s]


2018-11-01 00:00:00


100%|████████████████████████████████████████████████████████████████████████████████| 353/353 [05:44<00:00,  1.06s/it]


2018-12-01 00:00:00


100%|████████████████████████████████████████████████████████████████████████████████| 362/362 [06:07<00:00,  1.01it/s]


2019-01-01 00:00:00


100%|████████████████████████████████████████████████████████████████████████████████| 357/357 [05:55<00:00,  1.02s/it]
